name: "Integration test (using workflow call)"

on:
  workflow_dispatch:
    inputs:
      query_pack_url:
      language:
      instructions_url:
      pr_number:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Add status check target URL
        run: |
          gh api -X POST "/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA" \
            -f context=integration-test \
            -f description="integration-test-call.yml" \
            -f state=pending \
            -f target_url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}

  query:
    needs:
      - init
    uses: github/codeql-variant-analysis-action/.github/workflows/codeql-query.yml@set-query-timeout
    secrets:
      TEST_PAT: ${{ secrets.BOT_TOKEN }}

  fin:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - query
    steps:
      # Need to check out repo so that 'gh pr' will know the correct repo
      - uses: actions/checkout@v3

      - name: Update status check to state 'success'
        if: ${{ needs.query.result == 'success' }}
        run: |
          gh api -X POST "/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA" \
            -f context=integration-test \
            -f state=success \
            -f description="integration-test-call.yml" \
            -f target_url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Add success label to pull request
        if: ${{ needs.query.result == 'success' && github.event.inputs.pr_number != '' }}
        run: |
          # Get the branch without refs/heads/
          REF="$(git rev-parse --abbrev-ref HEAD)"
          # Only add the label if the workflow references the correct branch
          NUM_USAGES="$(grep 'uses: github/codeql-variant-analysis-action/' .github/workflows/codeql-query.yml | grep "@${REF}$" | wc -l)"
          if [ "$NUM_USAGES" == 2 ]; then
            gh pr edit "$PR_NUM" --add-label "integration tests succeeded"
          else
            echo "Detected $NUM_USAGES references to $REF branch"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUM: ${{ github.event.inputs.pr_number }}

      - name: Update status check to state 'failure'
        if: ${{ needs.query.result != 'success' }}
        run: |
          gh api -X POST "/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA" \
            -f context=integration-test \
            -f state=failure \
            -f description="integration-test-call.yml" \
            -f target_url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
