name: "Integration test (using workflow call)"

on:
  workflow_dispatch:
    inputs:
      query_pack_url:
      language:
      instructions_url:
      pr_number:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Add status check target URL
        run: |
          gh api -X POST "/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA" \
            -f context=integration-test \
            -f description="integration-test-call.yml" \
            -f state=pending \
            -f target_url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}

  query:
    needs:
      - init
    uses: github/codeql-variant-analysis-action/.github/workflows/codeql-query.yml@robertbrignull/tests_label
    secrets:
      TEST_PAT: ${{ secrets.BOT_TOKEN }}

  fin:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - query
    steps:
      - name: Update status check to state 'success'
        if: ${{ needs.query.result == 'success' }}
        run: |
          gh api -X POST "/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA" \
            -f context=integration-test \
            -f state=success \
            -f description="integration-test-call.yml" \
            -f target_url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Add success label to pull request
        if: ${{ needs.query.result == 'success' && github.event.inputs.pr_number != '' }}
        run: |
          gh api -X POST "/repos/$GITHUB_REPOSITORY/issues/${{ github.event.inputs.pr_number }}/labels" \
            -d '{"labels":["integration tests succeeded"]}'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Update status check to state 'failure'
        if: ${{ needs.query.result != 'success' }}
        run: |
          gh api -X POST "/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA" \
            -f context=integration-test \
            -f state=failure \
            -f description="integration-test-call.yml" \
            -f target_url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
